# Generated by Django 3.2.4 on 2021-08-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('birthdate', models.DateField(blank=True)),
                ('gender', models.CharField(blank=True, choices=[('Erkak', 'erkak'), ('Ayol', 'ayol')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.DateField(blank=True)),
                ('imdb', models.CharField(blank=True, choices=[('Komik', 'komik'), ('Drama', 'drama'), ('Detektiv', 'detektiv'), ('Jangari', 'jangari')], max_length=100)),
                ('actor', models.ManyToManyField(to='movie.Actor')),
            ],
        ),
    ]
