# Generated by Django 3.2.4 on 2021-08-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('Komik', 'komik'), ('Drama', 'drama'), ('Detektiv', 'detektiv'), ('Jangari', 'jangari')], default='a', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
