# Generated by Django 4.1.3 on 2022-11-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
