name: Netflix

on: [push]

jobs:
  run-tests:
    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: netflix.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Requirements
        run: pip install -r requariments.txt
      - name: Run Tests
        run: pytest
  deploy:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: netflix.agros.uz
          username: root
          key: ${{ secret.KEY }}
          script: |
            git pull
            systemctl restart gunicorn.service