name: Netflix

on: [push]

jobs:
  run-tests:
    runs-on: ubunutu-latest
    env:
      DJANGO_SETTINGS_MODULE: netflix.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install Requirements
        run: pip install -r requariments.txt
      - name: Run Tests
        run: pytest
